from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_EXPIRED = "AUTH_EXPIRED"
    BRAINSTORM_MODEL_ERROR = "BRAINSTORM_MODEL_ERROR"
    CHANNEL_FORBIDDEN = "CHANNEL_FORBIDDEN"
    FORBIDDEN = "FORBIDDEN"
    INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS"
    PHONE_CONFLICT = "PHONE_CONFLICT"
    QUICK_CALL_FAILED = "QUICK_CALL_FAILED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
