from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_EXPIRED = "AUTH_EXPIRED"
    CHANNEL_FORBIDDEN = "CHANNEL_FORBIDDEN"
    INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
